#!/usr/bin/env python

import logging
import spicerun

if __name__=='__main__':
    logging.basicConfig(format='%(asctime)s %(message)s',
                        level=logging.DEBUG)
    spicerun.main(*spicerun.getargs())

