#!/usr/bin/env python

import spice2hdf

if __name__=='__main__':
    args = getargs()
    logging.basicConfig(format='%(levelname)s:%(message)s',
                        level=args.verbose)
    spice2hdf.main(args)
