#!/usr/bin/env python

import logging
import spicerun

if __name__=='__main__':
    args = spicerun.getargs()
    logging.basicConfig(format='%(asctime)s %(message)s',
                        level=args.verbose)
    spicerun.main(args)

